[package]
name = "rust-google-hashcode-template"
version = "0.1.0"
authors = ["Malte Janz <malte.janz@yahoo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashcode-helpers = { path = "lib/hashcode-helpers" }
